### ISSUE TITLE
max_dec_steps=1 for decode mode

### ISSUE THREAD

**Issue by bhomass** [theamrzaki/text_summurization_abstractive_methods#9]
I can't make sense out of this setting. Why do you set max_dec_steps=1 for decode mode? You still have to decode the number of steps equals to size of the output summary, right? That is keep decoding until reaching the STOP word.

**Comment by bhomass** [comment]
the setting FLAGS.batch_size = FLAGS.beam_size is also hard to understand.

It seems you want batch_size = 1, and that one example in the batch will generatel beam_size beams.

**Comment by theamrzaki** [comment]
for the first comment , would you please tell me in which model did you find this , in able for me to be able to tackle this problem for you

**Comment by theamrzaki** [comment]
for the secound comment , batch size is the number of sentences that arrive to the system at each training step , this is different from beam search .

As beam search is an optimized method (better than greedy search) in producing the output , as it keeps in memory the most likely outputs , rather than working on all the possible outcomes , you can learn more about beam search from [here ](https://medium.com/@theamrzaki/beam-search-attention-for-text-summarization-made-easy-tutorial-5-3b7186df7086)

**Comment by theamrzaki** [comment]
hi @bhomass any updates ?

**Comment by bhomass** [comment]
I went thru the entire Beam Search code and figure out everything. Thanks.

**Comment by theamrzaki** [comment]
that's perfect
